#!/usr/bin/env python

# Copyright (c) 2016 IBM Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import sys
import os
import signal
import yaml
from daemonize import Daemonize
from molteniron import moltenirond

PID = "/var/run/moltenirond.pid"
YAML_CONF = "/usr/local/etc/molteniron/conf.yaml"

def get_moltenirond_pid():
    if not os.path.isfile(PID):
        return -1

    with open(PID) as fobj:
        lines = fobj.readlines()
        try:
            pid = int(lines[0])

            try:
                # Send harmless kill signal in order to test existance
                os.kill(pid, 0)
            except Exception:
                return -1

            return pid
        except Exception:
            return -1

def moltenirond_main():
    with open(YAML_CONF, "r") as fobj:
        conf = yaml.load(fobj)

        moltenirond.listener(conf)

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="Molteniron daemon helper")
    parser.add_argument("-c",
                        "--conf-dir",
                        action="store",
                        type=str,
                        dest="conf_dir",
                        help="The directory where configuration is stored")
    parser.add_argument("-p",
                        "--pid-dir",
                        action="store",
                        type=str,
                        dest="pid_dir",
                        help="The directory where PID information is stored")
    parser.add_argument("-v",
                        "--verbose",
                        action="store",
                        type=bool,
                        dest="verbose",
                        help="Set a verbose information mode")
    parser.add_argument("command", type=str, nargs=1, help="the command")

    args = parser.parse_args ()

    if args.conf_dir:
        if not os.path.isdir (args.conf_dir):
            msg = "Error: %s is not a valid directory" % (args.conf_dir, )
            print >> sys.stderr, msg
            sys.exit(1)

        YAML_CONF = os.path.realpath("%s/conf.yaml" % (args.conf_dir, ))

    if args.pid_dir:
        if not os.path.isdir (args.pid_dir):
            msg = "Error: %s is not a valid directory" % (args.pid_dir, )
            print >> sys.stderr, msg
            sys.exit(1)

        PID = os.path.realpath("%s/moltenirond.pid" % (args.pid_dir, ))

    if args.verbose:
        print "YAML_CONF = %s" % (YAML_CONF, )
        print "PID = %s" % (PID, )

    if len(args.command) != 1:
        msg = "Error: Expecting one command? Received: %s" % (args.command, )
        print >> sys.stderr, msg
        sys.exit (1)

    if args.command[0].upper().lower() == "start":
        pid = get_moltenirond_pid()
        if pid > 0:
            print >> sys.stderr, "Error: The daemon is already running"
            sys.exit(1)
        daemon = Daemonize(app="moltenirond",
                           pid=PID,
                           action=moltenirond_main)
        daemon.start()
    elif args.command[0].upper().lower() == "stop":
        pid = get_moltenirond_pid()
        if pid > 0:
            os.remove (PID)
            os.kill(pid, signal.SIGTERM)
        else:
            print >> sys.stderr, "Error: The daemon doesn't exist?"
            sys.exit(1)
    else:
        msg = "Error: Unknown command: %s" % (args.command[0], )
        print >> sys.stderr, msg
        sys.exit (1)
